" don't bother with vi compatibility
set nocompatible

filetype plugin indent on

" Plugins {{{

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'airblade/vim-gitgutter'
Plug 'christoomey/vim-tmux-navigator'
Plug 'mhinz/vim-startify'
"Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'MikeDacre/tmux-zsh-vim-titles'
"Plug 'jreybert/vimagit'
"Plug 'ap/vim-buftabline'
Plug 'bagrat/vim-buffet'

if isdirectory('/usr/local/opt/fzf')
  Plug '/usr/local/opt/fzf' | Plug 'junegunn/fzf.vim'
else
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
  Plug 'junegunn/fzf.vim'
endif

"Plug 'itchyny/lightline.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
"Plug 'claudiaj/lightline-molokai.vim'
"Plug 'shinchu/lightline-gruvbox.vim'

"----- Colorscheme -----
"Plug 'dracula/vim', { 'as': 'dracula' }
"Plug 'gruvbox-community/gruvbox'
"Plug 'altercation/vim-colors-solarized'
"Plug 'flazz/vim-colorschemes'
"Plug 'tomasr/molokai'
Plug 'arcticicestudio/nord-vim'

call plug#end()
" Required:
filetype plugin indent on

" }}}

" Color {{{

" enable syntax highlighting
syntax enable

colorscheme nord
"set background=dark

"set termguicolors

" }}}

" Spaces and Tabs {{{

set linespace=2
set backspace=2                " Fix broken backspace in some setups
set smarttab
set tabstop=4                  " actual tabs occupy 8 characters
set softtabstop=4              " insert mode tab and backspace use 2 spaces
set expandtab                  " expand tabs to spaces
set autoindent
set shiftwidth=2               " normal mode indentation commands use 2 spaces
" }}}

" UI Config {{{

set number                     " show line numbers
set showcmd
set cursorline
set ruler                      " show where you are
set wildmenu                   " show a navigable menu for tab completion
set wildmode=longest,list,full
set lazyredraw
set showmatch
set laststatus=2               " always show statusline
set noshowmode
set hidden
nnoremap <C-N> :bnext<CR>
nnoremap <C-P> :bprev<CR>

" }}}

" Searching {{{

set smartcase                  " case-sensitive search if any caps
set incsearch                  " search as you type
set hlsearch
set ignorecase                 " case-insensitive search
nnoremap <leader><space> :nohlsearch<CR>
" }}}

" Folding {{{

set foldenable          " enable folding
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " 10 nested fold max
" space open/closes folds
nnoremap <space> za
set foldmethod=indent   " fold based on indent level
" }}}

" Movement {{{

" }}}

" Leader Shortcuts {{{

let mapleader = ','
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l
noremap <leader>l :Align
nnoremap <leader>a :Ag<space>
"nnoremap <leader>b :CtrlPBuffer<CR>
"nnoremap <leader>d :NERDTreeToggle<CR>
nnoremap <leader>d :Explore<CR>
"nnoremap <leader>f :NERDTreeFind<CR>
"nnoremap <leader>t :CtrlP<CR>
"nnoremap <leader>T :CtrlPClearCache<CR>:CtrlP<CR>
nnoremap <leader><space> :call whitespace#strip_trailing()<CR>
nnoremap <leader>g :GitGutterToggle<CR>
noremap <silent> <leader>V :source ~/.vimrc<CR>:filetype detect<CR>:exe ":echo 'vimrc reloaded'"<CR>

"" Split
noremap <Leader>h :<C-u>split<CR>
noremap <Leader>v :<C-u>vsplit<CR>

"" Git
noremap <Leader>ga :Gwrite<CR>
noremap <Leader>gc :Gcommit<CR>
noremap <Leader>gsh :Gpush<CR>
noremap <Leader>gll :Gpull<CR>
noremap <Leader>gs :Gstatus<CR>
noremap <Leader>gb :Gblame<CR>
noremap <Leader>gd :Gvdiff<CR>
noremap <Leader>gr :Gremove<CR>

nmap <leader>1 <Plug>BuffetSwitch(1)
nmap <leader>2 <Plug>BuffetSwitch(2)
nmap <leader>3 <Plug>BuffetSwitch(3)
nmap <leader>4 <Plug>BuffetSwitch(4)
nmap <leader>5 <Plug>BuffetSwitch(5)
nmap <leader>6 <Plug>BuffetSwitch(6)
nmap <leader>7 <Plug>BuffetSwitch(7)
nmap <leader>8 <Plug>BuffetSwitch(8)
nmap <leader>9 <Plug>BuffetSwitch(9)
nmap <leader>0 <Plug>BuffetSwitch(10)

noremap <Tab> :bn<CR>
noremap <S-Tab> :bp<CR>
noremap <Leader><Tab> :Bw<CR>
noremap <Leader><S-Tab> :Bw!<CR>
noremap <C-t> :tabnew split<CR>
"" Close buffer
noremap <leader>c :bd<CR>

" keyboard shortcuts
vmap <leader>y "+y
vmap <leader>d "+d
nmap <leader>p "+p
nmap <leader>P "+P
vmap <leader>p "+p
vmap <leader>P "+P
" Don't copy the contents of an overwritten selection.
vnoremap p "_dP

" }}}

" Text Rendering {{{

set display+=lastline
set encoding=utf-8
set scrolloff=3                " show context above/below cursorline
" }}}

" Misc Settings {{{

set autoread                   " reload files when changed on disk, i.e. via `git checkout`
set backupcopy=yes             " see :help crontab
"" Copy/Paste/Cut
if has('unnamedplus')
  set clipboard=unnamed,unnamedplus
endif
set complete-=i
set directory-=.               " don't store swapfiles in the current directory
set gdefault

set list                       " show trailing whitespace
if has('multi_byte') && &encoding ==# 'utf-8'
  let &listchars = 'tab:▸ ,extends:❯,precedes:❮,nbsp:±'
else
  let &listchars = 'tab:> ,extends:>,precedes:<,nbsp:.'
endif

set nrformats-=octal
set wildignore=log/**,node_modules/**,target/**,tmp/**,*.rbc
set modelines=1

" Enable basic mouse behavior such as resizing buffers.
set mouse=a
if exists('$TMUX')  " Support resizing in tmux
  set ttymouse=xterm2
endif

" in case you forgot to sudo
cnoremap w!! %!sudo tee > /dev/null %

" Put all temporary files under the same directory.
" https://github.com/mhinz/vim-galore#handling-backup-swap-undo-and-viminfo-files
set backup
set backupdir   =$HOME/.vim/files/backup/
set backupext   =-vimbackup
set backupskip  =
set directory   =$HOME/.vim/files/swap//
set updatecount =100
set undofile
set undodir     =$HOME/.vim/files/undo/
set viminfo     ='100,n$HOME/.vim/files/info/viminfo

" }}}

" Plugin Settings {{{

" CTRL-P settings
let g:ctrlp_match_window = 'bottom,order:ttb,max:20'
let g:ctrlp_switch_buffer = 0
let g:ctrlp_working_path_mode = 0

let g:NERDSpaceDelims=1
let g:gitgutter_enabled = 1

let g:startify_custom_header=''

" Airline config
let g:airline_theme='nord'
" let g:airline_theme='gotham'
" let g:airline#extensions#hunks#non_zero_only = 1
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#enabled = 1 " Enable the list of buffers
let g:airline#extensions#tabline#fnamemod = ':t' " Show just the filename
let g:airline_skip_empty_sections = 1
let g:airline#extensions#virtualenv#enabled = 1

"*****************************************************************************
"" Convenience variables
"*****************************************************************************

" vim-airline
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

if !exists('g:airline_powerline_fonts')
  let g:airline#extensions#tabline#left_sep = ' '
  let g:airline#extensions#tabline#left_alt_sep = '|'
  let g:airline_left_sep          = '▶'
  let g:airline_left_alt_sep      = '»'
  let g:airline_right_sep         = '◀'
  let g:airline_right_alt_sep     = '«'
  let g:airline#extensions#branch#prefix     = '⤴' "➔, ➥, ⎇
  let g:airline#extensions#readonly#symbol   = '⊘'
  let g:airline#extensions#linecolumn#prefix = '¶'
  let g:airline#extensions#paste#symbol      = 'ρ'
  let g:airline_symbols.linenr    = '␊'
  let g:airline_symbols.branch    = '⎇'
  let g:airline_symbols.paste     = 'ρ'
  let g:airline_symbols.paste     = 'Þ'
  let g:airline_symbols.paste     = '∥'
  let g:airline_symbols.whitespace = 'Ξ'
else
  let g:airline#extensions#tabline#left_sep = ''
  let g:airline#extensions#tabline#left_alt_sep = ''

  " powerline symbols
  let g:airline_left_sep = ''
  let g:airline_left_alt_sep = ''
  let g:airline_right_sep = ''
  let g:airline_right_alt_sep = ''
  let g:airline_symbols.branch = ''
  let g:airline_symbols.readonly = ''
  let g:airline_symbols.linenr = ''
endif

"" fzf.vim
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.pyc,__pycache__
let $FZF_DEFAULT_COMMAND =  "find * -path '*/\.*' -prune -o -path 'node_modules/**' -prune -o -path 'target/**' -prune -o -path 'dist/**' -prune -o  -type f -print -o -type l -print 2> /dev/null"

" Fix Cursor in TMUX
if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

let g:tzvt_vim_force_tmux_title_change = 1

" Netrw Settings
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 1

" ACME Syntax bei ASM Files
autocmd BufNewFile,BufRead *.asm set syntax=acme.vim

" ********** F U N C T I O N S ***********
" returns all modified files of the current git repo
" `2>/dev/null` makes the command fail quietly, so that when we are not
" in a git repo, the list will be empty
function! s:gitModified()
    let files = systemlist('git ls-files -m 2>/dev/null')
    return map(files, "{'line': v:val, 'path': v:val}")
endfunction

" same as above, but show untracked files, honouring .gitignore
function! s:gitUntracked()
    let files = systemlist('git ls-files -o --exclude-standard 2>/dev/null')
    return map(files, "{'line': v:val, 'path': v:val}")
endfunction

let g:startify_lists = [
        \ { 'type': 'files',     'header': ['   MRU']            },
        \ { 'type': 'dir',       'header': ['   MRU '. getcwd()] },
        \ { 'type': 'sessions',  'header': ['   Sessions']       },
        \ { 'type': 'bookmarks', 'header': ['   Bookmarks']      },
        \ { 'type': function('s:gitModified'),  'header': ['   git modified']},
        \ { 'type': function('s:gitUntracked'), 'header': ['   git untracked']},
        \ { 'type': 'commands',  'header': ['   Commands']       },
        \ ]


" }}}

" vim:foldmethod=marker:foldlevel=2
