

""" Automatically create needed files and folders on first run (*nix only) {{{
    call system('mkdir -p $HOME/.vim/{autoload,bundle,undo}')
    if !filereadable($HOME.'/.vimrc.local') | call system('touch $HOME/.vimrc.local') | endif
""" }}}
""" vim-plug plugin manager {{{
    " Automatic installation
    " https://github.com/junegunn/vim-plug/wiki/faq#automatic-installation
    if empty(glob('~/.vim/autoload/plug.vim'))
        let g:clone_details = 'https://github.com/junegunn/vim-plug.git $HOME/.vim/bundle/vim-plug'
        silent call system('git clone --depth 1 '. g:clone_details)
        if v:shell_error | silent call system('git clone ' . g:clone_details) | endif
        silent !ln -s $HOME/.vim/bundle/vim-plug/plug.vim $HOME/.vim/autoload/plug.vim
        augroup FirstPlugInstall
            autocmd! VimEnter * PlugInstall --sync | source $MYVIMRC
        augroup END
    endif

    " Default to same plugin directory as vundle etc
    call plug#begin('~/.vim/bundle')

    " Ranger
    Plug 'rafaqz/ranger.vim'
    Plug 'scrooloose/nerdTree'

    " Airline
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'

    " Fuzzy finder (files, mru, etc)
    Plug 'ctrlpvim/ctrlp.vim'

    " Undo history visualizer
    Plug 'mbbill/undotree'

    " Git wrapper inside Vim
    Plug 'tpope/vim-fugitive'
    Plug 'airblade/vim-gitgutter'

"    Plug 'gruvbox-community/gruvbox'
    Plug 'arcticicestudio/nord-vim'

    " A fancy start screen, shows MRU etc.
    Plug 'mhinz/vim-startify'

    Plug 'ryanoasis/vim-devicons'
    Plug 'rafi/awesome-vim-colorschemes'
    Plug 'chriskempson/base16-vim'
    Plug 'ap/vim-css-color'

" Initalize plugin system
call plug#end()


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" User interface
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" https://stackoverflow.com/a/33380495/1076493
if !exists('g:syntax_on')
  syntax enable
endif

if (&term =~# 'xterm') || (&term =~# 'screen')
  set t_Co=256
endif

colorscheme nord
set background=dark

" make background transparent
hi Normal ctermbg=NONE
hi EndOfBuffer ctermbg=NONE
hi LineNr ctermbg=234


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" General settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set path+=**                    " Searches current directory recursively.
set wildmenu                    " Display all matches when tab complete.
set incsearch                   " Incremental search
set hidden                      " Needed to keep multiple buffers open
set nobackup                    " No auto backups
set noswapfile                  " No swap
if !exists('g:syntax_on')
  syntax enable
endif

"if (&term =~# 'xterm') || (&term =~# 'screen')
"  set t_Co=256 " Set if term supports 256 colors.
"endif
set number relativenumber       " Display line numbers
set clipboard=unnamedplus       " Copy/paste between vim and other programs.
syntax enable
"let g:rehash256 = 1

set modelines=0
set nu
set rnu
set nowrap
set ruler
set cursorline
set colorcolumn=80
set noerrorbells
set encoding=utf-8
set smarttab                    " Be smart using tabs ;)
set tabstop=2                   " One tab == two spaces.
set shiftwidth=2                " One tab == two spaces.
set softtabstop=2
set expandtab                   " Use spaces instead of tabs.
set noshiftround
set scrolloff=8
set backspace=indent,eol,start
set matchpairs+=<:>             " use % to jump between pairs
set path=$PWD/**                " enable fuzzy finding in the vim command line
set wildmenu                    " enable fuzzy menu
set wildignore+=**/.git/**,**/__pycache__/**,**/venv/**,**/node_modules/**,**/dist/**,**/build/**,*.o,*.pyc,*.swp
set hidden
set ttyfast 					" Rendering
set laststatus=2 				" Status bar
set showcmd 					" Last line
set noshowmode
set nohls
set incsearch
set ignorecase
set smartcase
set showmatch
set listchars=tab:>·,trail:~,extends:>,precedes:<,space:·
"set listchars=tab:→\ ,eol:¬,nbsp:¬,trail:⋅,extends:❯,precedes:❮
set list

" Return to last edit position when opening files
augroup LastPosition
  autocmd! BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \     exe "normal! g`\"" |
    \ endif
augroup END

set autoread                              " refresh if changed
set noswapfile
set nobackup                              " disable backups
" Persistent undo. Requires Vim 7.3
if has('persistent_undo') && exists('&undodir')
  set undodir=$HOME/.vim/undo/            " where to store undofiles
  set undofile                            " enable undofile
  set undolevels=500                      " max undos stored
  set undoreload=10000                    " buffer stored undos
endif


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Keybindings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:mapleader=',' " Remap <Leader>

" Quickly edit/source .vimrc
noremap <Leader>ve :edit $HOME/.vim/vimrc<CR>
noremap <Leader>vs :source $HOME/.vim/vimrc<CR>

" Yank(copy) to system clipboard
noremap <Leader>y "+y

" Toggle pastemode, doesn't indent
set pastetoggle=<F3>

" Toggle folding
" http://vim.wikia.com/wiki/Folding#Mappings_to_toggle_folds
nnoremap <silent> <Space> @=(foldlevel('.')?'za':"\<Space>")<CR>

" Toggle relativenumber
nnoremap <silent> <Leader>r :set relativenumber!<CR>

" Treat wrapped lines as normal lines
nnoremap <expr> k v:count == 0 ? 'gk' : 'k'
nnoremap <expr> j v:count == 0 ? 'gj' : 'j'

" Quickly switch buffers
nnoremap <Leader>n :bnext<CR>
nnoremap <Leader>p :bprevious<CR>
nnoremap <Leader>f :b#<CR>
nnoremap <Leader>1 :1b<CR>
nnoremap <Leader>2 :2b<CR>
nnoremap <Leader>3 :3b<CR>
nnoremap <Leader>4 :4b<CR>
nnoremap <Leader>5 :5b<CR>
nnoremap <Leader>6 :6b<CR>
nnoremap <Leader>7 :7b<CR>
nnoremap <Leader>8 :8b<CR>
nnoremap <Leader>9 :9b<CR>
nnoremap <Leader>0 :10b<CR>

" Highlight last inserted text
nnoremap gV '[V']

" Remap ESC to ii
:imap ii <Esc>

" Quickly edit/source .vimrc
noremap <Leader>ve :edit $HOME/.vim/vimrc<CR>
noremap <Leader>vs :source $HOME/.vim/vimrc<CR>

" Useful mappings for managing tabs
map <leader>tn :tabnew<cr>
map <leader>to :tabonly<cr>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove
map <leader>t<leader> :tabnext

" Tab Navigation
nnoremap th  :tabfirst<CR>
nnoremap tk  :tabnext<CR>
nnoremap tj  :tabprev<CR>
nnoremap tl  :tablast<CR>
nnoremap tt  :tabedit<Space>
nnoremap tn  :tabnext<Space>
nnoremap tm  :tabm<Space>
nnoremap td  :tabclose<CR>

" CtrlP keys
nnoremap <Leader>pp :CtrlP<CR>
nnoremap <Leader>pf :CtrlP<CR>
nnoremap <Leader>pm :CtrlPMRUFiles<CR>
nnoremap <Leader>pr :CtrlPMRUFiles<CR>
nnoremap <Leader>pb :CtrlPBuffer<CR>

" Ranger
map <leader>rr :RangerEdit<cr>
map <leader>rv :RangerVSplit<cr>
map <leader>rs :RangerSplit<cr>
map <leader>rt :RangerTab<cr>
map <leader>ri :RangerInsert<cr>
map <leader>ra :RangerAppend<cr>
map <leader>rc :set operatorfunc=RangerChangeOperator<cr>g@
map <leader>rd :RangerCD<cr>
map <leader>rld :RangerLCD<cr>

" Toggle undo history tree
nnoremap <F5> :UndotreeToggle<CR>

nnoremap <C-n> :NERDTreeToggle <cr>

" Opens a new tab with the current buffer's path
" Super useful when editing files in the same directory
map <leader>te :tabedit <C-r>=expand("%:p:h")<cr>/

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Splits and Tabbed Files
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set splitbelow splitright

" Remap splits navigation to just CTRL + hjkl
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Make adjusing split sizes a bit more friendly
noremap <silent> <C-Left> :vertical resize +3<CR>
noremap <silent> <C-Right> :vertical resize -3<CR>
noremap <silent> <C-Up> :resize +3<CR>
noremap <silent> <C-Down> :resize -3<CR>

" Change 2 split windows from vert to horiz or horiz to vert
map <Leader>th <C-w>t<C-w>H
map <Leader>tk <C-w>t<C-w>K

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Vim Fugitive Keybinds
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gc :Gcommit -v -q<CR>
nnoremap <leader>ga :Gcommit --amend<CR>
nnoremap <leader>gt :Gcommit -v -q %<CR>
nnoremap <leader>gd :Gdiff<CR>
nnoremap <leader>ge :Gedit<CR>
nnoremap <leader>gr :Gread<CR>
nnoremap <leader>gw :Gwrite<CR><CR>
nnoremap <leader>gl :silent! Glog<CR>
nnoremap <leader>gp :Ggrep<Space>
nnoremap <leader>gm :Gmove<Space>
nnoremap <leader>gb :Git branch<Space>
nnoremap <leader>go :Git checkout<Space>
nnoremap <leader>gps :Dispatch! git push<CR>
nnoremap <leader>gpl :Dispatch! git pull<CR>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Functions and/or fancy keybinds
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Toggle syntax highlighting
function! ToggleSyntaxHighlighting()
  if exists('g:syntax_on')
    syntax off
  else
    syntax enable
  endif
endfunction
nnoremap <Leader>s :call ToggleSyntaxHighlighting()<CR>

""" Highlight characters past 79, toggle with <Leader>h {{{
""" You might want to override this function and its variables with
""" your own in .vimrc.last which might set for example colorcolumn or
""" even the textwidth. See https://github.com/timss/vimconf/pull/4
let g:overlength_enabled = 0
highlight OverLength ctermbg=238 guibg=#444444

function! ToggleOverLength()
  if g:overlength_enabled == 0
    match OverLength /\%79v.*/
    let g:overlength_enabled = 1
    echo 'OverLength highlighting turned on'
  else
    match
    let g:overlength_enabled = 0
    echo 'OverLength highlighting turned off'
  endif
endfunction
nnoremap <Leader>h :call ToggleOverLength()<CR>

" Toggle text wrapping, wrap on whole words
" For more info see: http://stackoverflow.com/a/2470885/1076493
function! WrapToggle()
  if &wrap
    set list
    set nowrap
  else
    set nolist
    set wrap
  endif
endfunction
nnoremap <Leader>w :call WrapToggle()<CR>

" Strip trailing whitespace, return to cursor at save
function! StripTrailingWhitespace()
  let l:save = winsaveview()
  %s/\s\+$//e
  call winrestview(l:save)
endfunction

augroup StripTrailingWhitespace
  autocmd!
  autocmd FileType c,cpp,cfg,conf,css,html,perl,python,sh,tex,yaml
    \ autocmd BufWritePre <buffer> :call
    \ StripTrailingWhitespace()
augroup END

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugin Settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Startify
let g:startify_bookmarks = [
  \ $HOME . '/.vim/vimrc', $HOME . '/.xmonad/xmonad.hs',
  \ $HOME . '/.config/i3/config', $HOME . '/.config/zsh/.zshrc'
  \ ]
let g:startify_custom_header = [
  \ '   ViM-World (c)2021 by EddieFAF',
  \ ''
  \ ]
let g:startify_files_number = 5

" CtrlP
" Don't recalculate files on start (slow)
let g:ctrlp_clear_cache_on_exit = 0
let g:ctrlp_working_path_mode = 'ra'

" Don't split in Startify
let g:ctrlp_reuse_window = 'startify'

" Netrw
let g:netrw_banner = 0
let g:netrw_list_hide = '^\.$'
let g:netrw_liststyle = 3

" Airline
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#whitespace#enabled = 1
let g:airline#extensions#hunks#non_zero_only = 1
let g:airline_powerline_fonts=0
let g:airline#extensions#tabline#enabled=1  " buffers at the top as tabs
" let g:airline#extensions#tabline#show_tabs=0
let g:airline#extensions#tabline#show_tab_type=0
let g:airline#extensions#tmuxline#enabled=0
let g:airline_theme = 'nord'
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

let g:airline_symbols.linenr = ''
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.readonly = ''

let g:airline#extensions#quickfix#quickfix_text = 'QF'
let g:airline#extensions#quickfix#location_text = 'LL'

" disable unused extensions (performance)
let g:airline#extensions#ctrlp#color_template = 'insert'
let g:airline#extensions#bufferline#enabled = 1
let g:airline#extensions#capslock#enabled   = 0
let g:airline#extensions#csv#enabled        = 0
let g:airline#extensions#ctrlspace#enabled  = 0
let g:airline#extensions#eclim#enabled      = 1
let g:airline#extensions#nrrwrgn#enabled    = 0
let g:airline#extensions#promptline#enabled = 0
let g:airline#extensions#syntastic#enabled  = 0
let g:airline#extensions#taboo#enabled      = 0
let g:airline#extensions#tagbar#enabled     = 0
let g:airline#extensions#virtualenv#enabled = 0

" FZF 
let g:fzf_colors =
  \ { 'fg':      ['fg', 'Normal'],
    \ 'bg':      ['bg', 'Normal'],
    \ 'hl':      ['fg', 'Comment'],
    \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
    \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
    \ 'hl+':     ['fg', 'Statement'],
    \ 'info':    ['fg', 'PreProc'],
    \ 'border':  ['fg', 'Ignore'],
    \ 'prompt':  ['fg', 'Conditional'],
    \ 'pointer': ['fg', 'Exception'],
    \ 'marker':  ['fg', 'Keyword'],
    \ 'spinner': ['fg', 'Label'],
    \ 'header':  ['fg', 'Comment'] }

" vim-devicons for folders
let g:DevIconsEnableFoldersOpenClose = 1
let g:webdevicons_conceal_nerdtree_brackets = 0
let g:WebDevIconsOS = 'Darwin'
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}

function GetGitBranch()
  let branchName = FugitiveHead()
  if branchName != ""
    return "\  \|\ " . branchName
  endif
  return ""
endfunction


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Status Line
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" The lightline.vim theme
"let g:lightline = {
"      \ 'colorscheme': 'gruvbox',
"      \ }


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Mouse Scrolling
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set mouse=nicr


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Other Stuff
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Removes pipes | that act as seperators on splits
set fillchars+=vert:\ 
set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Local config, will overwrite anything above. Generally use this
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
  if filereadable($HOME.'/.vimrc.local')
    source $HOME/.vimrc.local
  endif
