local M = {
  'lukas-reineke/indent-blankline.nvim',
  enabled = false,
  event = { 'BufReadPost', 'BufNewFile' },
  opts = {
    indentLine_enabled = 1,
    char = '┊',
    filetype_exclude = {
      'startify',
      'dashboard',
      'dotooagenda',
      'log',
      'fugitive',
      'gitcommit',
      'packer',
      'vimwiki',
      'markdown',
      'json',
      'txt',
      'vista',
      'help',
      'todoist',
      'NvimTree',
      'neo-tree',
      'peekaboo',
      'git',
      'TelescopePrompt',
      'undotree',
      'flutterToolsOutline',
      '', -- for all buffers without a file type
    },
    buftype_exclude = { 'terminal', 'nofile' },
    show_trailing_blankline_indent = false,
    show_first_indent_level = false,
    show_current_context = true,
    --    char_list = { '|', '¦', '┆', '┊' },
    use_treesitter = true,
    show_end_of_line = true,
    space_char = ' ',
    context_patterns = {
      'class',
      'function',
      'method',
      'block',
      'list_literal',
      'selector',
      '^if',
      '^table',
      'if_statement',
      'while',
      'for',
    },
  },
}

return M
