local M = {
  -- {
  --   'lukas-reineke/indent-blankline.nvim',
  --   event = { 'BufReadPost', 'BufNewFile' },
  --   enabled = false,
  --   opts = {
  --     buftype_exclude = {
  --       'nofile',
  --       'terminal',
  --     },
  --     filetype_exclude = {
  --       'help',
  --       'startify',
  --       'aerial',
  --       'alpha',
  --       'dashboard',
  --       'lazy',
  --       'neogitstatus',
  --       'NvimTree',
  --       'neo-tree',
  --       'Trouble',
  --       'ranger',
  --       'rnvimr',
  --     },
  --     context_patterns = {
  --       'class',
  --       'return',
  --       'function',
  --       'method',
  --       '^if',
  --       '^while',
  --       'jsx_element',
  --       '^for',
  --       '^object',
  --       '^table',
  --       'block',
  --       'arguments',
  --       'if_statement',
  --       'else_clause',
  --       'jsx_element',
  --       'jsx_self_closing_element',
  --       'try_statement',
  --       'catch_clause',
  --       'import_statement',
  --       'operation_type',
  --     },
  --     show_trailing_blankline_indent = false,
  --     use_treesitter = true,
  --     char = '▏',
  --     context_char = '▏',
  --     show_current_context = true,
  --   },
  -- },
  {
    'lukas-reineke/indent-blankline.nvim',
    enabled = true,
    event = { 'BufReadPost', 'BufNewFile' },
    opts = {
      indentLine_enabled = 1,
      char = '┊',
      filetype_exclude = {
        'startify',
        'dashboard',
        'dotooagenda',
        'log',
        'fugitive',
        'gitcommit',
        'packer',
        'vimwiki',
        'markdown',
        'json',
        'txt',
        'vista',
        'help',
        'todoist',
        'NvimTree',
        'neo-tree',
        'peekaboo',
        'git',
        'TelescopePrompt',
        'undotree',
        'flutterToolsOutline',
        '', -- for all buffers without a file type
      },
      buftype_exclude = { 'terminal', 'nofile' },
      show_trailing_blankline_indent = false,
      show_first_indent_level = false,
      show_current_context = false,
      show_current_context_start = true,
      --    char_list = { '|', '¦', '┆', '┊' },
      use_treesitter = true,
      space_char = ' ',
      context_patterns = {
        'class',
        'function',
        'method',
        'block',
        'list_literal',
        'selector',
        '^if',
        '^table',
        'if_statement',
        'while',
        'for',
        'return',
        '^while',
        'jsx_element',
        '^for',
        '^object',
        'arguments',
        'else_clause',
        'jsx_element',
        'jsx_self_closing_element',
        'try_statement',
        'catch_clause',
        'import_statement',
        'operation_type',
      },
    },
  },
}
return M
