local M = {
  {
    'lukas-reineke/indent-blankline.nvim',
    enabled = true,
    event = { 'BufReadPost', 'BufNewFile' },
    opts = {
      indentLine_enabled = 1,
      char = '┊',
      --      char_list = { '|', '¦', '┆', '┊' },
      filetype_exclude = {
        'startify',
        'dashboard',
        'dotooagenda',
        'log',
        'fugitive',
        'gitcommit',
        'packer',
        'vimwiki',
        'markdown',
        'json',
        'txt',
        'vista',
        'help',
        'todoist',
        'NvimTree',
        'neo-tree',
        'peekaboo',
        'git',
        'TelescopePrompt',
        'undotree',
        'flutterToolsOutline',
        '', -- for all buffers without a file type
      },
      buftype_exclude = { 'terminal', 'nofile' },
      show_trailing_blankline_indent = false,
      show_first_indent_level = true,
      show_current_context = false,
      show_current_context_start = true,
      use_treesitter = true,
      space_char = ' ',
      context_patterns = {
        'class',
        'function',
        'method',
        'block',
        'list_literal',
        'selector',
        '^if',
        '^table',
        'if_statement',
        'while',
        'for',
        'return',
        '^while',
        'jsx_element',
        '^for',
        '^object',
        'arguments',
        'else_clause',
        'jsx_element',
        'jsx_self_closing_element',
        'try_statement',
        'catch_clause',
        'import_statement',
        'operation_type',
      },
    },
  },
}
return M
