#! /bin/sh

# Start pywal theming
#wal -R

# make sure all processes are killed
killall -q compton
killall -q sxhkd
killall -q dunst
killall -q polybar
killall -q dropbox
killall -q Nextcloud-3.0.1-x86_64.AppImage

# wait until the processes have been shut down (just in case)
while pgrep -u $UID -x compton >/dev/null; do sleep 1; done
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
while pgrep -u $UID -x dropbox >/dev/null; do sleep 1;done
while pgrep -u $UID -x Nextcloud-3.0.1-x86_64.AppImage >/dev/null; do sleep 1;done

### AUTOSTART ###
compton -b -f --config ~/.config/compton.conf &
~/.config/polybar/launch.sh &
sxhkd &
dunst -config ~/.config/dunst/dunstrc &
dropbox start -i &
~/Downloads/Nextcloud-3.0.1-x86_64.AppImage &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nm-applet &
~/.fehbg &
xrdb .Xresources &

xset r rate 300 50 & # makes key repeat faster


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config focused_border_color "#bd93f9"
bspc config active_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a vlc state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

