#! /bin/sh

# Start pywal theming
#wal -R

# make sure all processes are killed
killall -q compton
killall -q sxhkd
killall -q dunst
killall -q polybar
killall -q dropbox
killall -q Nextcloud-3.0.1-x86_64.AppImage

# wait until the processes have been shut down (just in case)
while pgrep -u $UID -x compton >/dev/null; do sleep 1; done
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
while pgrep -u $UID -x dropbox >/dev/null; do sleep 1;done
while pgrep -u $UID -x Nextcloud-3.0.1-x86_64.AppImage >/dev/null; do sleep 1;done

### AUTOSTART ###
xrdb .Xresources &
wal -i "/home/eddie/Bilder/wallpapers"
source "/home/eddie/.cache/wal/colors.sh"
compton -b -f --config ~/.config/compton.conf &
~/.config/polybar/launch.sh &
sxhkd &

/usr/bin/dunst \
    -lb "${color0:-#F0F0F0}" \
    -nb "${color0:-#F0F0F0}" \
    -cb "${color0:-#F0F0F0}" \
    -lf "${color7:=#000000}" \
    -cf "${color7:=#000000}" \
    -nf "${color7:=#000000}" \
    -frame_color "${color1:=#F0F0F0}" \
    -config ~/.config/dunst/dunstrc &

dropbox start -i &
~/Downloads/Nextcloud-3.0.1-x86_64.AppImage &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
nm-applet &
#~/.fehbg &

xset r rate 300 50 & # makes key repeat faster


bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#bspc config normal_border_color "#44475a"
#bspc config focused_border_color "#bd93f9"
#bspc config active_border_color "#ff79c6"
#bspc config presel_feedback_color "#6272a4"

bspc config normal_border_color $color0
bspc config focused_border_color $color7
bspc config active_border_color $color1
bspc config urgent_border_color $color1
bspc config presel_feedback_color $color7

# rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a vlc state=floating
bspc rule -a celluloid state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule --add thunderbird desktop='^3'
bspc rule --add zathura state=tiled
bspc rule --add "*:pavucontrol" state=floating
bspc rule --add "*:floating" state=floating
bspc rule --add doublecmd state=floating
bspc rule --add Gnome-calculator state=floating
bspc rule --add Blueman-manager state=floating

bspc rule -a dropdown sticky=on state=floating hidden=on
urxvt -geometry 100x30 -name dropdown -e "zsh -i" &

