# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
bindkey -e
# End of lines configured by zsh-newuser-install

export TERM=xterm-256color
export LANG=de_DE.UTF-8

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# The following lines were added by compinstall
zstyle :compinstall filename '/home/eddie/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

### Added by Zplugin's installer
source '/home/eddie/.zplugin/bin/zplugin.zsh'
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
### End of Zplugin installer's chunk

zplugin light zdharma/fast-syntax-highlighting
zplugin snippet OMZ::plugins/git/git.plugin.zsh
zplugin load agkozak/agkozak-zsh-prompt
#zplugin ice depth=1; zplugin light romkatv/powerlevel10k
zplugin snippet OMZ::plugins/common-aliases/common-aliases.plugin.zsh
zplugin snippet OMZ::plugins/debian/debian.plugin.zsh
zplugin snippet OMZ::plugins/tmux/tmux.plugin.zsh
#zplugin light "chrissicool/zsh-256color"
zplugin light "zsh-users/zsh-autosuggestions"
zplugin ice atclone"dircolors -b LS_COLORS > c.zsh" atpull'%atclone' pick"c.zsh"
zplugin load trapd00r/LS_COLORS

# Aliases for EXA
# general use
alias ls='exa'                                 # ls
alias l='exa -lbF --git'                       # list, size, type, git
alias ll='exa -lbGF --git'                     # long list
alias llm='exa -lbGF --git --sort=modified'    # long list, modified date sort
alias la='exa -lbhHigUmuSa --time-style=long-iso --git --color-scale'  # all list
alias lx='exa -lbhHigUmuSa@ --time-style=long-iso --git --color-scale' # all + extended list

# speciality views
alias lS='exa -1'                              # one column, just names
alias lt='exa --tree --level=2' # tree

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
#[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
