# Allow local customizations in the ~/.zshrc_local_before file
if [ -f ~/.zshrc_local_before ]; then
    source ~/.zshrc_local_before
fi

setopt MENUCOMPLETE

export TERM=xterm-256color
export LANG=de_DE.UTF-8
# Load colors
autoload -U colors && colors

###########
# History #
###########

# History file
HISTFILE="$HOME/.zsh_history"

# The maximum number of events stored in history memory list
HISTSIZE=50000

# The maximum number of history events to save in the history file
SAVEHIST=10000

# Record timestamp of command in HISTFILE
setopt extended_history

# Delete duplicates first
setopt hist_expire_dups_first

# Ignore duplicated commands history list
setopt hist_ignore_dups

# Ignore commands that start with space
setopt hist_ignore_space

# Show command with history expansion to user before running it
setopt hist_verify

# Add commands to HISTFILE in order of execution
setopt inc_append_history

# Share command history data
setopt share_history

# Remove blank lines from history
setopt hist_reduce_blanks

# cd without cd
setopt auto_cd

# Do not autoselect the first completion entry
unsetopt menu_complete

# Show completion menu on successive tab press
setopt auto_menu

# Do not set cursor to the end of the word if completion is started
setopt complete_in_word

# If a completion is performed with the cursor within a word, and a full completion
# is inserted, the cursor is moved to the end of the word
setopt always_to_end

# Print job notifications in the long format by default
setopt long_list_jobs

# Allow comments even in interactive shells
setopt interactivecomments

# Fancy tees and cats
setopt multios

# Make cd push the old directory onto the directory stack
setopt auto_pushd

# Do not push multiple copies of the same directory onto the directory stack
setopt pushd_ignore_dups

# Exchanges the meanings of '+' and '-'' when used with a number to specify a directory
# in the stack
setopt pushdminus
# Edit command in vim with ctrl-v
autoload edit-command-line; zle -N edit-command-line
bindkey '^v' edit-command-line

# [Ctrl-RightArrow] - move forward one word
bindkey '^[[1;5C' forward-word

# [Ctrl-LeftArrow] - move backward one word
bindkey '^[[1;5D' backward-word

# [Shift-Tab] - move through the completion menu backwards
bindkey '${terminfo[kcbt]}' reverse-menu-complete

# [Backspace] - delete backward
bindkey '^?' backward-delete-char

# [Delete] - delete forward
bindkey '^[[3~' delete-char

# [Home] - Go to beginning of line
bindkey  '^[[H' beginning-of-line

# [End] - Go to end of line
bindkey  '^[[F' end-of-line

# FIXME
# [Ctrl-r] - Search backward incrementally for a specified string
bindkey '^r' history-incremental-search-backward


# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

### Added by Zplugin's installer
source '/home/eddie/.zinit/bin/zinit.zsh'
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zplugin installer's chunk

zinit snippet OMZ::plugins/git/git.plugin.zsh
zinit load agkozak/agkozak-zsh-prompt
#zinit ice depth=1; zplugin light romkatv/powerlevel10k
zinit snippet OMZ::plugins/common-aliases/common-aliases.plugin.zsh
zinit snippet OMZ::plugins/debian/debian.plugin.zsh
zinit snippet OMZ::plugins/docker-compose/docker-compose.plugin.zsh
zinit snippet OMZ::plugins/tmux/tmux.plugin.zsh
zinit load agkozak/zsh-z

zinit ice atclone"dircolors -b LS_COLORS > clrs.zsh" \
    atpull'%atclone' pick"clrs.zsh" nocompile'!' \
    atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”'
zinit light trapd00r/LS_COLORS

zinit light le0me55i/zsh-extract
zinit load zpm-zsh/ssh
zinit load jreese/zsh-titles

# ogham/exa, replacement for ls
zinit ice wait"2" lucid from"gh-r" as"program" mv"exa* -> exa"
zinit light ogham/exa

zinit ice wait blockf atpull'zinit creinstall -q .'
zinit light zsh-users/zsh-completions

zinit ice wait atinit"zpcompinit; zpcdreplay"
zinit light zdharma/fast-syntax-highlighting

zinit ice wait atload"_zsh_autosuggest_start"
zinit light zsh-users/zsh-autosuggestions

##############
# Completion #
##############

# Completion init
zstyle :compinstall filename "~/.zshrc"
autoload -Uz compinit
compinit

# Include hidden files in completions
_comp_options+=(globdots)

# Gimme nice tab selection
zstyle ':completion:*:*:*:*:*' menu select

# Completion insensitive to case and hyphens/underscores
zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|=*' 'l:|=* r:|=*'

# Complete . and .. special directories
zstyle ':completion:*' special-dirs true
# Colors for completions
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# Use cache for fast completion
zstyle ':completion::complete:*' use-cache 1

# Cache path
zstyle ':completion::complete:*' cache-path "~/.cache/zsh"

### set common functions
#############

function my_ip() # Get IP adress.
{
   curl ifconfig.co
}

# Find a file with a pattern in name:
function ff()
{
    find . -type f -iname '*'"$*"'*' -ls ;
}

function sysinfo()   # Get current host related info.
{
    echo -e "\n${BRed}System Informations:$NC " ; uname -a
    echo -e "\n${BRed}Online User:$NC " ; w -hs |
             cut -d " " -f1 | sort | uniq
    echo -e "\n${BRed}Date :$NC " ; date
    echo -e "\n${BRed}Server stats :$NC " ; uptime
    echo -e "\n${BRed}Memory stats :$NC " ; free
    echo -e "\n${BRed}Public IP Address :$NC " ; my_ip
    echo -e "\n${BRed}Open connections :$NC "; netstat -pan --inet;
    echo -e "\n${BRed}CPU info :$NC "; cat /proc/cpuinfo ;
    echo -e "\n"
}

# Creates an archive (*.tar.gz) from given directory.
function maketar() { tar cvzf "${1%%/}.tar.gz"  "${1%%/}/"; }

# Create a ZIP archive of a file or folder.
function makezip() { zip -r "${1%%/}.zip" "$1" ; }

function my_ps() { ps $@ -u $USER -o pid,%cpu,%mem,bsdtime,command ; }

mcd () {
    mkdir -p $1
    cd $1
}

# Aliases for EXA
# general use
alias ls='exa'                                 # ls
alias l='exa -lbF --git'                       # list, size, type, git
alias ll='exa -lbGF --git'                     # long list
alias llm='exa -lbGF --git --sort=modified'    # long list, modified date sort
alias la='exa -lbhHigUmuSa --time-style=long-iso --git --color-scale'  # all list
alias lx='exa -lbhHigUmuSa@ --time-style=long-iso --git --color-scale' # all + extended list

# speciality views
alias lS='exa -1'                              # one column, just names
alias lt='exa --tree --level=2' # tree

### Set alias
#############
alias cls="clear"
alias ..="cd .."
alias cd..="cd .."
alias ...='../..'
alias ....='../../..'
#alias ll="ls -lisa --color=auto"
alias home="cd ~"
#alias df="df -ahiT --total"
alias mkdir="mkdir -pv"
alias mkfile="touch"
#alias rm="rm -rfi"
alias userlist="cut -d: -f1 /etc/passwd"
#alias ls="ls -CF --color=auto"
alias lsl="ls -lhFA | less"
alias free="free -mt"
#alias du="du -ach | sort -h"
alias ps="ps auxf"
alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"
alias wget="wget -c"
alias histg="history | grep"
alias myip="curl http://ipecho.net/plain; echo"
alias logs="find /var/log -type f -exec file {} \; | grep 'text' | cut -d' ' -f1 | sed -e's/:$//g' | grep -v '[0-9]$' | xargs tail -f"
alias folders='find . -maxdepth 1 -type d -print0 | xargs -0 du -sk | sort -rn'
alias grep='grep --color=auto'


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
#[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Allow local customizations in the ~/.zshrc_local_after file
if [ -f ~/.zshrc_local_after ]; then
    source ~/.zshrc_local_after
fi

