# move the rest of the prompt to the right
right_format = """$time"""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

[time]
time_format = "%T"
format = "$time($style) "
style = "dimmed green"
disabled = false

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

#[aws]
#symbol = "aws "

#[cobol]
#symbol = "cobol "

#[conda]
#symbol = "conda "

#[crystal]
#symbol = "cr "

#[cmake]
#symbol = "cmake "

#[dart]
#symbol = "dart "

#[deno]
#symbol = "deno "

#[dotnet]
#symbol = ".NET "

[directory]
#read_only = " ro"
read_only = " "
truncation_length = 5
truncation_symbol = "…/"
#style = "blue"
fish_style_pwd_dir_length = 2

#[docker_context]
#symbol = "docker "

#[elixir]
#symbol = "exs "

#[elm]
#symbol = "elm "

#[git_branch]
#symbol = "git "

#[golang]
#symbol = "go "

#[hg_branch]
#symbol = "hg "

#[java]
#symbol = "java "

#[julia]
#symbol = "jl "

#[kotlin]
#symbol = "kt "

#[nodejs]
#symbol = "nodejs "

#[memory_usage]
#symbol = "memory "

#[nim]
#symbol = "nim "

#[nix_shell]
#symbol = "nix "

#[ocaml]
#symbol = "ml "

#[package]
#symbol = "pkg "
#disabled = true

#[perl]
#symbol = "pl "

#[php]
#symbol = "php "

#[purescript]
#symbol = "purs "

#[python]
#symbol = "py "

#[ruby]
#symbol = "rb "

#[rust]
#symbol = "rs "

#[scala]
#symbol = "scala "

#[swift]
#symbol = "swift "

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "
disabled = true

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

