;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
;background = ${xrdb:color0:#222}
background = #10141c
background-alt = #444
;foreground = ${xrdb:color7:#222}
foreground = #D8DEE9
foreground-alt = #555
primary = #ffb52a
secondary = #e60053
alert = #bd2c40
comment = #6272a4
current = #44475a

;; Material Colors
red = #e53935
pink = #d81b60
purple = #8e24aa
deep-purple = #5e35b1
indigo = #3949ab
blue = #1e88e5
light-blue = #039be5
cyan = #00acc1
teal = #00897b
green = #43a047
light-green = #7cb342
lime = #c0ca33
yellow = #fdd835
amber = #ffb300
orange = #fb8c00
deep-orange = #f4511e
brown = #6d4c41
grey = #757575
blue-gray = #546e7a

fg = ${rxdb:i3wm.foreground:#F8F8F2}
bg = ${rxdb:i3wm.background:#282A36}
col0 = ${rxdb:i3wm.color0:#000000}
col1 = ${rxdb:i3wm.color1:#FF5555}
col2 = ${rxdb:i3wm.color2:#50FA7B}
col3 = ${rxdb:i3wm.color3:#F1FA8C}
col4 = ${rxdb:i3wm.color4:#BD93F9}
col5 = ${rxdb:i3wm.color5:#FF79C6}
col6 = ${rxdb:i3wm.color6:#8BE9FD}
col7 = ${rxdb:i3wm.color7:#BFBFBF}
col8 = ${rxdb:i3wm.color8:#4D4D4D}
col9 = ${rxdb:i3wm.color9:#FF6E67}
col10 = ${rxdb:i3wm.color10:#5AF78E}
col11 = ${rxdb:i3wm.color11:#F4F99D}
col12 = ${rxdb:i3wm.color12:#CAA9FA}
col13 = ${rxdb:i3wm.color13:#FF92D0}
col14 = ${rxdb:i3wm.color14:#9AEDFE}
col15 = ${rxdb:i3wm.color15:#E6E6E6}

xcolor0 = ${xrdb:color0}
xcolor1 = ${xrdb:color1}
xcolor2 = ${xrdb:color2}
xcolor3 = ${xrdb:color3}
xcolor4 = ${xrdb:color4}
xcolor5 = ${xrdb:color5}
xcolor6 = ${xrdb:color6}
xcolor7 = ${xrdb:color7}
xcolor8 = ${xrdb:color8}
xcolor9 = ${xrdb:color9}
xcolor10 = ${xrdb:color10}
xcolor11 = ${xrdb:color11}
xcolor12 = ${xrdb:color12}
xcolor13 = ${xrdb:color13}
xcolor14 = ${xrdb:color14}
xcolor15 = ${xrdb:color15}

[bar/default]
monitor = DVI-1
width = 100%
height = 24
offset-x = 0%
offset-y = 0%
radius = 0.0
fixed-center = true

background = ${colors.xcolor0}
foreground = ${colors.xcolor7}

line-size = 2
line-color = ${colors.xcolor7}

;overline-size = 2
;overline-color = ${colors.primary}

border-size = 0
border-color = #D8DEE9

padding-left = 0
padding-right = 1

module-margin-left = 1
module-margin-right = 1

font-0 = HackNerdFont:style=Bold:size=10;1
;font-2 = Font Awesome 5 Free:style=Solid:size=10;1
font-1 = "waffle:size=12;2"
font-2 = FontAwesome:style=Regular:size=10;1
;font-4 = Font Awesome 5 Brands:style=Regular:size=10;1
;font-5 = Material Design Icons:style=Regular:size=11;1
font-3 = JetBrainsMono:style=Bold:size=10;1
font-4 = Weather Icons:size=12;1

modules-left   = menu i3 bspwm
modules-center = xwindow
modules-right  = openweathermap-detailed volume updates-apt filesystem dropbox-isrunning cpu memory date xkeyboard powermenu  

separator =""
 
enable-ipc = true

tray-position = right
tray-padding = 0

wm-restack = bspwm
;wm-restack = i3

;override-redirect = true

scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

;scroll-up = i3wm-wsnext
;scroll-down = i3wm-wsprev

cursor-click = pointer
cursor-scroll = ns-resize



[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%
; Available tags:
;   <label> (default)
format = <label>
format-prefix = " "
format-prefix-foreground = ${colors.blue}
;;format-background = ${color.bg}
;;format-foreground = ${color.ac}
;;format-padding = 4
label-empty = Mint
label-empty-foreground = #707880

format-foreground = ${colors.xcolor7}
format-background = ${colors.xcolor0}

[module/menu-apps]
type = custom/menu

; If true, <label-toggle> will be to the left of the menu items (default).
; If false, it will be on the right of all the items.
expand-right = true

; "menu-LEVEL-N" has the same properties as "label-NAME" with
; the additional "exec" property
;
; Available exec commands:
;   menu-open-LEVEL
;   menu-close
; Other commands will be executed using "/bin/sh -c $COMMAND"

menu-0-0 = Browsers
menu-0-0-exec = menu-open-1
menu-0-1 = conv
menu-0-1-exec = menu-open-2

menu-1-0 = ungoogled
menu-1-0-exec =  /opt/ungoogled-chromium_83.0.4103.97-1.1_linux/chrome-wrapper &
menu-1-1 = conn
menu-1-1-exec = connman-gtk &

menu-2-0 = tel
menu-2-0-exec = telegram-desktop &
menu-2-1 = pcmanfm
menu-2-1-exec = pcmanfm &

; Available tags:
;   <label-toggle> (default) - gets replaced with <label-(open|close)>
;   <menu> (default)
; If expand-right is true, the default will be "<label-toggle><menu>" and the
; other way around otherwise.
; Note that if you use <label-toggle> you must also include
; the definition for <label-open>
; format = <label-toggle><menu>

label-open = 󰙀 apps
label-close = 󰅙

; Optional item separator
; Default: none
label-separator = "  "

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = scroll lock
blacklist-1 = caps lock

format-prefix = "   "
format-prefix-foreground = ${colors.xcolor7}
format-prefix-underline = ${colors.xcolor5}

label-layout = %layout%
label-layout-underline = ${colors.xcolor5}

label-indicator-padding = 1
label-indicator-margin = 0
label-indicator-background = ${colors.xcolor5}
label-indicator-on-underline = ${colors.xcolor2}

label-indicator-on-foreground = ${colors.xcolor2}
label-indicator-off-foreground = ${colors.xcolor8}

indicator-icon-0 = num lock;NL;NL

label-indicator-on = %icon%
label-indicator-off = %icon%

[module/filesystem]
type = internal/fs
interval = 10

mount-0 = /
fixed-values = true
;label-mounted-foreground =#88C0D0

format-mounted = <label-mounted>
format-mounted-prefix = 
format-mounted-prefix-foreground = ${colors.xcolor6}

format-unmounted = <label-unmounted>
format-unmounted-prefix = 
format-unmounted-prefix-foreground = ${colors.orange}

label-mounted = " %free%"
label-unmounted = %mountpoint%: not mounted
label-unmounted-foreground = ${colors.foreground-alt}

format-mounted-underline = ${colors.xcolor6}

[module/bspwm]
type = internal/bspwm
pin-workspaces = false

ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5
ws-icon-5 = 6;6
ws-icon-6 = 7;7
ws-icon-7 = 8;8
ws-icon-8 = 9;9
ws-icon-9 = 10;10

format = <label-state> <label-mode>

label-monitor = %name%

label-focused = %icon%
label-focused-foreground = ${colors.xcolor0}
label-focused-background = ${colors.xcolor7}
;label-focused-background = ${colors.bg}
label-focused-underline= ${colors.primary}
label-focused-padding = 1

label-occupied = %name%
label-occupied-padding = 1
label-occupied-foreground = ${colors.xcolor1}
label-occupied-background = ${colors.xcolor0}

label-urgent = %name%!
;label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-urgent-foreground = ${colors.xcolor1}
label-urgent-background = ${colors.xcolor0}

label-empty = %name%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 1


[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

; Only show workspaces on the same output as the bar
;pin-workspaces = true

ws-icon-0 = 1;1: 
ws-icon-1 = 2;2: 
ws-icon-2 = 3;3: 
ws-icon-3 = 4;4: 
ws-icon-4 = 5;5: 
ws-icon-5 = 6;6: 
ws-icon-6 = 7;7: 
ws-icon-7 = 8;8: 
ws-icon-8 = 9;9: 
ws-icon-9 = 10;10: 
 

;label-font = 0
label-mode-padding = 1
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %name%
label-focused-background = #4D4D4D
label-focused-foreground = #F8F8F2
label-focused-underline= #8BE9FD
label-focused-padding = 3

; unfocused = Inactive workspace on any monitor
label-unfocused = %name%
label-unfocused-padding = 3

; visible = Active workspace on unfocused monitor
label-visible = %name%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 3

; Separator in between workspaces
;label-separator = 


[module/mpd]
type = internal/mpd
format-online = <label-song>  <icon-prev> <icon-stop> <toggle> <icon-next>

icon-prev = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 

label-song-maxlen = 25
label-song-ellipsis = true

[module/cpu]
type = internal/cpu
interval = 0.5
format = <label>
format-prefix = 
format-prefix-foreground = ${colors.xcolor5}
format-underline = ${colors.xcolor5}
label = %percentage:2%%

[module/mem]
type = custom/script
exec = free -m | sed -n 's/^Mem:\s\+[0-9]\+\s\+\([0-9]\+\)\s.\+/\1/p'
format = <label>
label = 󰳡 %output%
label-padding = 1

[module/memory]
type = internal/memory
interval = 3
format = <label>
format-prefix = 
format-prefix-foreground = ${colors.xcolor4}
format-underline = ${colors.xcolor4}
label = " %mb_used%"

bar-used-indicator =
bar-used-width = 20
bar-used-foreground-0 = #55aa55
bar-used-foreground-1 = #557755
bar-used-foreground-2 = #f5a70a
bar-used-foreground-3 = #ff5555
bar-used-fill = ▐
bar-used-empty = ▐
bar-used-empty-foreground = #444444

; Only applies if <ramp-used> is used
ramp-used-0 = ▁
ramp-used-1 = ▂
ramp-used-2 = ▃
ramp-used-3 = ▄
ramp-used-4 = ▅
ramp-used-5 = ▆
ramp-used-6 = ▇
ramp-used-7 = █

; Only applies if <ramp-free> is used
ramp-free-0 = ▁
ramp-free-1 = ▂
ramp-free-2 = ▃
ramp-free-3 = ▄
ramp-free-4 = ▅
ramp-free-5 = ▆
ramp-free-6 = ▇
ramp-free-7 = █

[module/wlan]
type = internal/network
interface = wlp2s0
interval = 3.0


format-connected = <label-connected>
format-connected-underline = #9f78e1
label-connected = 󰤨 %essid%

 
format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = ${colors.foreground-alt}

[module/eth]
type = internal/network
interface = eth1
interval = 3.0

format-connected-underline = #55aa55
format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected = %local_ip%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

[module/date]
type = internal/date
interval = 1

date =
date-alt = " %d.%m.%Y"

time = %H:%M
time-alt = %H:%M:%S

format-prefix =  
format-prefix-padding = 1
format-prefix-foreground = ${colors.xcolor7}
format-prefix-background = ${colors.xcolor0}
;format-underline = #8BE9FD
label = %date% %time%
label-background = ${colors.xcolor0}
label-foreground = ${colors.xcolor7}
label-padding-left = 0
label-padding-right = 2

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume> <bar-volume>
label-volume = VOL %percentage%%
label-volume-foreground = ${root.foreground}

label-muted = 🔇 muted
label-muted-foreground = #666

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/cpu-graph]
type = internal/cpu
interval = 0.08
;format = " <ramp-coreload>"
format = " <ramp-coreload>"
format-margin = 1
ramp-coreload-0 = ▁ 
ramp-coreload-0-foreground = ${colors.fg}
ramp-coreload-1 = ▂ 
ramp-coreload-1-foreground = ${colors.fg}
ramp-coreload-2 = ▃ 
ramp-coreload-2-foreground = ${colors.adapta-lightgreen}
ramp-coreload-3 = ▄ 
ramp-coreload-3-foreground = ${colors.adapta-green}
ramp-coreload-4 = ▅ 
ramp-coreload-4-foreground = ${colors.adapta-yellow}
ramp-coreload-5 = ▆ 
ramp-coreload-5-foreground = ${colors.adapta-yellow}
ramp-coreload-6 = ▇ 
ramp-coreload-6-foreground = ${colors.adapta-red}
ramp-coreload-7 = █ 
ramp-coreload-7-foreground = ${colors.adapta-red}
ramp-coreload-font = 3
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format-underline = ${colors.foreground-alt}
format-padding = 3



[module/alsa]
type = internal/alsa

format-volume = <bar-volume> <label-volume> 
format-prefix = ""
label-volume = " %percentage%%"
label-volume-foreground = ${root.foreground}
 
;format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
label-muted =  muted

; Only applies if <ramp-volume> is used
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-font = 3

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/powermenu]
type = custom/menu

expand-right = true

format-spacing = 1

label-open = 
label-open-foreground = ${colors.xcolor4}

label-close =  cancel
label-close-foreground = ${colors.xcolor4}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot

menu-2-0 = power off
menu-2-0-exec = sudo poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

[module/dropbox-isrunning]
type = custom/script
exec = ~/bin/polybar/dropbox-isrunning.sh
interval = 5
click-left = ~/bin/polybar/dropbox-isrunning.sh --toggle &
format-underline = ${colors.xcolor2}

[module/updates-apt]
type = custom/script
exec = ~/bin/polybar/updates-apt.sh
interval = 600

[module/openweathermap-detailed]
type = custom/script
exec = ~/bin/polybar/openweathermap-detailed.sh
interval = 600
label-font = 5

[module/volume]
type = internal/alsa

; Soundcard to be used
; Usually in the format hw:# where # is the card number
; You can find the different card numbers in `/proc/asound/cards`
;;master-soundcard = default
;;speaker-soundcard = default
;;headphone-soundcard = default

; Name of the master, speaker and headphone mixers
; Use the following command to list available mixer controls:
; $ amixer scontrols | sed -nr "s/.*'([[:alnum:]]+)'.*/\1/p"
; If master, speaker or headphone-soundcard isn't the default, 
; use `amixer -c # scontrols` instead where # is the number 
; of the master, speaker or headphone soundcard respectively
;
; Default: Master
;;master-mixer = Master

; Optionally define speaker and headphone mixers
; Default: none
;;speaker-mixer = Speaker
; Default: none
;;headphone-mixer = Headphone

; NOTE: This is required if headphone_mixer is defined
; Use the following command to list available device controls
; $ amixer controls | sed -r "/CARD/\!d; s/.*=([0-9]+).*name='([^']+)'.*/printf '%3.0f: %s\n' '\1' '\2'/e" | sort
; You may also need to use `amixer -c # controls` as above for the mixer names
; Default: none
;;headphone-id = 9

; Use volume mapping (similar to amixer -M and alsamixer), where the increase in volume is linear to the ear
; Default: false
;;mapped = true

; Interval for volume increase/decrease (in percent points)
; Default: 5
;;interval = 5

; Available tags:
;   <label-volume> (default)
;   <ramp-volume>
;   <bar-volume>
format-volume = <label-volume> <bar-volume>

; Available tags:
;   <label-muted> (default)
;   <ramp-volume>
;   <bar-volume>
format-muted = <label-muted>

; Available tokens:
;   %percentage% (default)
label-volume = 
label-volume-foreground = ${colors.fg}

; Available tokens:
;   %percentage% (default
format-muted-prefix = 
label-muted = " MUTED"
label-muted-foreground = ${colors.col1}

; Only applies if <ramp-volume> is used
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 
ramp-volume-4 = 

; Only applies if <bar-volume> is used
bar-volume-width = 10
bar-volume-gradient = false

bar-volume-indicator = 
bar-volume-indicator-foreground = ${colors.primary}
bar-volume-indicator-font = 2

bar-volume-fill = 
bar-volume-foreground-0 = ${colors.col2}
bar-volume-foreground-1 = ${colors.col10}
bar-volume-foreground-2 = ${colors.col3}
bar-volume-foreground-3 = ${colors.col1}
bar-volume-fill-font = 2

bar-volume-empty = 
bar-volume-empty-foreground = ${colors.background-alt}
bar-volume-empty-font = 2

; If defined, it will replace <ramp-volume> when
; headphones are plugged in to `headphone_control_numid`
; If undefined, <ramp-volume> will be used for both
; Only applies if <ramp-volume> is used
ramp-headphones-0 = 
ramp-headphones-1 = 

[module/menu]
type = custom/text
content = 
 
content-background = ${colors.col4}
content-foreground = ${colors.fg}
content-padding = 1
 
;click-left = dmenu_run -b -l 5 -p Search -fn "Misc Termsyn" -nb "#1D1F28" -nf "#f7f7f7" -sb "#1E88E5" -sf "#202020"
click-left = rofi -show run -theme ~/.config/rofi/themes/dracula.rasi
;click-left = "jgmenu_run >/dev/null 2>&1 &"

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
;pseudo-transparency = false

[global/wm]
margin-top = 5
margin-bottom = 5

; vim:ft=dosini

